# 1 "data/maps/SootopolisCity_House2/scripts.pory"

# 2 "data/maps/SootopolisCity_House2/scripts.pory"
SootopolisCity_House2_MapScripts::
# 3 "data/maps/SootopolisCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_House2/scripts.pory"

# 5 "data/maps/SootopolisCity_House2/scripts.pory"
SootopolisCity_House2_EventScript_ExpertF::
# 6 "data/maps/SootopolisCity_House2/scripts.pory"
	lock
# 7 "data/maps/SootopolisCity_House2/scripts.pory"
	faceplayer
# 8 "data/maps/SootopolisCity_House2/scripts.pory"
	msgbox SootopolisCity_House2_Text_CityIsQuiet, MSGBOX_DEFAULT
# 9 "data/maps/SootopolisCity_House2/scripts.pory"
	release
# 10 "data/maps/SootopolisCity_House2/scripts.pory"
	end
# 11 "data/maps/SootopolisCity_House2/scripts.pory"

# 12 "data/maps/SootopolisCity_House2/scripts.pory"

# 13 "data/maps/SootopolisCity_House2/scripts.pory"
SootopolisCity_House2_Text_CityIsQuiet:
# 14 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "This town is so nice and quiet…\p"
# 15 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "We do get visitors now that Marina is\n"
# 16 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "here.\p"
# 17 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "It's nice, it keeps the town alive.$"
