FallarborTown_CozmosHouse_MapScripts::
	.byte 0


Godzilland_House1_Scientist::
# 4 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	lock
# 5 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	faceplayer
# 6 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	msgbox GodzillandBiodiversity, MSGBOX_AUTOCLOSE
# 7 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	release
	end


Godzilland_House1_ScientistHusband::
# 19 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	lock
# 20 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	faceplayer
# 21 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	msgbox GodzillandBiodiversity, MSGBOX_AUTOCLOSE
# 22 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	release
	end


GodzillandBiodiversity::
# 11 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "I'm a biologist.\p"
	.string "Some POKéMON species can only be found\n"
	.string "in certain areas.\p"
	.string "Godzilland has a fascinating ecosystem!$"

Godzilland_ScientistHusband::
# 26 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "I love POKéMON!\p"
	.string "When my husband told me we were gonna \n"
	.string "move to an island full of unique POKéMON \l"
	.string "I was ecstatic!$"
