# 1 "data/maps/RustboroCity_House2/scripts.pory"

# 2 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_MapScripts::
# 3 "data/maps/RustboroCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_House2/scripts.pory"

# 5 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_PokefanF::
# 6 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
# 7 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 8 "data/maps/RustboroCity_House2/scripts.pory"

# 9 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_LittleGirl::
# 10 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
# 11 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 12 "data/maps/RustboroCity_House2/scripts.pory"

# 13 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_TrainerSchoolExcellent:
# 14 "data/maps/RustboroCity_House2/scripts.pory"
	.string "We are big music fans in this house!\p"
# 15 "data/maps/RustboroCity_House2/scripts.pory"
	.string "So naturally, we were thrilled to see\n"
# 16 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Hozier settling here.$"
# 17 "data/maps/RustboroCity_House2/scripts.pory"

# 18 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_RoxanneKnowsALot:
# 19 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Hozier knows a lot about POKéMON.\p"
# 20 "data/maps/RustboroCity_House2/scripts.pory"
	.string "He's really strong, too!$"
