GjuhaCave_MapScripts::
	.byte 0


GjuhaCave_Scientist::
# 4 "data/maps/GjuhaCave/scripts.pory"
	lock
# 5 "data/maps/GjuhaCave/scripts.pory"
	faceplayer
# 6 "data/maps/GjuhaCave/scripts.pory"
	msgbox GjuhaCave_Scientist_Text_0
# 7 "data/maps/GjuhaCave/scripts.pory"
	release
	end


GjuhaCave_Scientist_Text_0:
# 6 "data/maps/GjuhaCave/scripts.pory"
	.string "This cave is a bit of a mystery.\p"
	.string "We don't know why it's so cold in here,\n"
	.string "but at least it's convenient in summer.$"
