# 1 "data/maps/Route125/scripts.pory"

# 2 "data/maps/Route125/scripts.pory"
Route125_MapScripts::
# 3 "data/maps/Route125/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route125_OnTransition
# 4 "data/maps/Route125/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route125_OnLoad
# 5 "data/maps/Route125/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route125_OnFrame
# 6 "data/maps/Route125/scripts.pory"
	.byte 0
# 7 "data/maps/Route125/scripts.pory"

# 8 "data/maps/Route125/scripts.pory"
Route125_OnTransition:
# 9 "data/maps/Route125/scripts.pory"
	call_if_set FLAG_SYS_WEATHER_CTRL, Common_EventScript_SetAbnormalWeather
# 10 "data/maps/Route125/scripts.pory"
	call_if_eq VAR_SHOULD_END_ABNORMAL_WEATHER, 1, AbnormalWeather_EventScript_HideMapNamePopup
# 11 "data/maps/Route125/scripts.pory"
	call_if_eq VAR_ABNORMAL_WEATHER_LOCATION, ABNORMAL_WEATHER_ROUTE_125_WEST, AbnormalWeather_StartKyogreWeather
# 12 "data/maps/Route125/scripts.pory"
	call_if_eq VAR_ABNORMAL_WEATHER_LOCATION, ABNORMAL_WEATHER_ROUTE_125_EAST, AbnormalWeather_StartKyogreWeather
# 13 "data/maps/Route125/scripts.pory"
	end
# 14 "data/maps/Route125/scripts.pory"

# 15 "data/maps/Route125/scripts.pory"
Route125_OnLoad:
# 16 "data/maps/Route125/scripts.pory"
	call_if_eq VAR_ABNORMAL_WEATHER_LOCATION, ABNORMAL_WEATHER_ROUTE_125_WEST, AbnormalWeather_EventScript_PlaceTilesRoute125West
# 17 "data/maps/Route125/scripts.pory"
	call_if_eq VAR_ABNORMAL_WEATHER_LOCATION, ABNORMAL_WEATHER_ROUTE_125_EAST, AbnormalWeather_EventScript_PlaceTilesRoute125East
# 18 "data/maps/Route125/scripts.pory"
	end
# 19 "data/maps/Route125/scripts.pory"

# 20 "data/maps/Route125/scripts.pory"
Route125_OnFrame:
# 21 "data/maps/Route125/scripts.pory"
	map_script_2 VAR_SHOULD_END_ABNORMAL_WEATHER, 1, AbnormalWeather_EventScript_EndEventAndCleanup_1
# 22 "data/maps/Route125/scripts.pory"
	.2byte 0
# 23 "data/maps/Route125/scripts.pory"

# 24 "data/maps/Route125/scripts.pory"
Route125_EventScript_Nolen::
# 25 "data/maps/Route125/scripts.pory"
	trainerbattle_single TRAINER_NOLEN, Route125_Text_NolenIntro, Route125_Text_NolenDefeat
# 26 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_NolenPostBattle, MSGBOX_AUTOCLOSE
# 27 "data/maps/Route125/scripts.pory"
	end
# 28 "data/maps/Route125/scripts.pory"

# 29 "data/maps/Route125/scripts.pory"
Route125_EventScript_Stan::
# 30 "data/maps/Route125/scripts.pory"
	trainerbattle_single TRAINER_STAN, Route125_Text_StanIntro, Route125_Text_StanDefeat
# 31 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_StanPostBattle, MSGBOX_AUTOCLOSE
# 32 "data/maps/Route125/scripts.pory"
	end
# 33 "data/maps/Route125/scripts.pory"

# 34 "data/maps/Route125/scripts.pory"
Route125_EventScript_Tanya::
# 35 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_TanyaPostBattle, MSGBOX_AUTOCLOSE
# 36 "data/maps/Route125/scripts.pory"
	end
# 37 "data/maps/Route125/scripts.pory"

# 38 "data/maps/Route125/scripts.pory"
Route125_EventScript_Sharon::
# 39 "data/maps/Route125/scripts.pory"
	trainerbattle_single TRAINER_SHARON, Route125_Text_SharonIntro, Route125_Text_SharonDefeat
# 40 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_SharonPostBattle, MSGBOX_AUTOCLOSE
# 41 "data/maps/Route125/scripts.pory"
	end
# 42 "data/maps/Route125/scripts.pory"

# 43 "data/maps/Route125/scripts.pory"
Route125_EventScript_Ernest::
# 44 "data/maps/Route125/scripts.pory"
	trainerbattle_single TRAINER_ERNEST_1, Route125_Text_ErnestIntro, Route125_Text_ErnestDefeat, Route125_EventScript_RegisterErnest
# 45 "data/maps/Route125/scripts.pory"
	specialvar VAR_RESULT, ShouldTryRematchBattle
# 46 "data/maps/Route125/scripts.pory"
	goto_if_eq VAR_RESULT, TRUE, Route125_EventScript_RematchErnest
# 47 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_ErnestPostBattle, MSGBOX_DEFAULT
# 48 "data/maps/Route125/scripts.pory"
	release
# 49 "data/maps/Route125/scripts.pory"
	end
# 50 "data/maps/Route125/scripts.pory"

# 51 "data/maps/Route125/scripts.pory"
Route125_EventScript_RegisterErnest::
# 52 "data/maps/Route125/scripts.pory"
	special PlayerFaceTrainerAfterBattle
# 53 "data/maps/Route125/scripts.pory"
	waitmovement 0
# 54 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_ErnestRegister, MSGBOX_DEFAULT
# 55 "data/maps/Route125/scripts.pory"
	register_matchcall TRAINER_ERNEST_1
# 56 "data/maps/Route125/scripts.pory"
	release
# 57 "data/maps/Route125/scripts.pory"
	end
# 58 "data/maps/Route125/scripts.pory"

# 59 "data/maps/Route125/scripts.pory"
Route125_EventScript_RematchErnest::
# 60 "data/maps/Route125/scripts.pory"
	trainerbattle_rematch TRAINER_ERNEST_1, Route125_Text_ErnestRematchIntro, Route125_Text_ErnestRematchDefeat
# 61 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_ErnestRematchPostBattle, MSGBOX_AUTOCLOSE
# 62 "data/maps/Route125/scripts.pory"
	end
# 63 "data/maps/Route125/scripts.pory"

# 64 "data/maps/Route125/scripts.pory"
Route125_EventScript_Kim::
# 65 "data/maps/Route125/scripts.pory"
	trainerbattle_double TRAINER_KIM_AND_IRIS, Route125_Text_KimIntro, Route125_Text_KimDefeat, Route125_Text_KimNotEnoughMons
# 66 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_KimPostBattle, MSGBOX_AUTOCLOSE
# 67 "data/maps/Route125/scripts.pory"
	end
# 68 "data/maps/Route125/scripts.pory"

# 69 "data/maps/Route125/scripts.pory"
Route125_EventScript_Iris::
# 70 "data/maps/Route125/scripts.pory"
	trainerbattle_double TRAINER_KIM_AND_IRIS, Route125_Text_IrisIntro, Route125_Text_IrisDefeat, Route125_Text_IrisNotEnoughMons
# 71 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_IrisPostBattle, MSGBOX_AUTOCLOSE
# 72 "data/maps/Route125/scripts.pory"
	end
# 73 "data/maps/Route125/scripts.pory"

# 74 "data/maps/Route125/scripts.pory"
Route125_EventScript_Presley::
# 75 "data/maps/Route125/scripts.pory"
	trainerbattle_single TRAINER_PRESLEY, Route125_Text_PresleyIntro, Route125_Text_PresleyDefeat
# 76 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_PresleyPostBattle, MSGBOX_AUTOCLOSE
# 77 "data/maps/Route125/scripts.pory"
	end
# 78 "data/maps/Route125/scripts.pory"

# 79 "data/maps/Route125/scripts.pory"
Route125_EventScript_Auron::
# 80 "data/maps/Route125/scripts.pory"
	trainerbattle_single TRAINER_AURON, Route125_Text_AuronIntro, Route125_Text_AuronDefeat
# 81 "data/maps/Route125/scripts.pory"
	msgbox Route125_Text_AuronPostBattle, MSGBOX_AUTOCLOSE
# 82 "data/maps/Route125/scripts.pory"
	end
