gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "I'm Goblin, big POKéMON nerd and even \n"
	.string "bigger The Last Dinner Party Fan!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "People live alongside POKéMON, and live\n"
	.string "plenty of adventures with them.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us!\p"
	.string "Some people are really good at this,\n"
	.string "like TLDP.\p"
	.string "They have a show coming up, and they \n"
	.string "are cordially inviting whoever beats \l"
	.string "them all in POKéMON battle!\p"
	.string "I'm definitely gonna try to challenge\n"
	.string "them, how about you?\p"
	.string "Who knows, you might succeed!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But first, tell me a bit about \n"
	.string "yourself...$"

gText_Birch_BoyOrGirl::
	.string "What style are you more into?\n"
	.string "That's like super important… $"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're the {PLAYER} who's been a fan\n"
	.string "for a while.\p"
	.string "I get it now!\p"
	.string "$"


gText_Birch_AreYouReady::
	.string "Alright, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and TLDP await!"
	.string "$" 
