gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is Amy, but everyone\n"
	.string "calls me PARLOUR CHEF\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "Some people are really good at this,\n"
	.string "like The Last Dinner Party.\p"
	.string "They have a show coming up,\n"
	.string "and they are cordially inviting \l"
	.string "whoever beats them all in POKéMON \l"
	.string "battle.\p"
	.string "You strike me as a motivated fan,\n"
	.string "how about you try your luck?\p"
	.string "Who knows, you might succeed!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But first, tell me a bit about \n"
	.string "yourself...$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?\l"
	.string "Not that it really matters...$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're the {PLAYER}{KUN} who's been a fan\n"
	.string "for a while.\p"
	.string "I get it now!$"


gText_Birch_AreYouReady::
	.string "Alright, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and TLDP await!$" 
