MercyTown_MapScripts::
	.byte 0


MercyTown_Route7Sign::
# 4 "data/maps/MercyTown/scripts.pory"
	lock
# 5 "data/maps/MercyTown/scripts.pory"
	msgbox MercyTown_Route7Sign_Text_0, MSGBOX_AUTOCLOSE
# 6 "data/maps/MercyTown/scripts.pory"
	release
	end


MercyTown_Route8Sign::
# 11 "data/maps/MercyTown/scripts.pory"
	lock
# 12 "data/maps/MercyTown/scripts.pory"
	msgbox MercyTown_Route8Sign_Text_0, MSGBOX_AUTOCLOSE
# 13 "data/maps/MercyTown/scripts.pory"
	release
	end


MercyTown_ConcertHallSign::
# 18 "data/maps/MercyTown/scripts.pory"
	lock
# 19 "data/maps/MercyTown/scripts.pory"
	msgbox MercyTown_ConcertHallSign_Text_0, MSGBOX_AUTOCLOSE
# 20 "data/maps/MercyTown/scripts.pory"
	release
	end


MercyTown_WelcomeToMercyTownSign::
# 25 "data/maps/MercyTown/scripts.pory"
	lock
# 26 "data/maps/MercyTown/scripts.pory"
	msgbox MercyTown_WelcomeToMercyTownSign_Text_0, MSGBOX_AUTOCLOSE
# 27 "data/maps/MercyTown/scripts.pory"
	release
	end


MercyTown_Route7Sign_Text_0:
# 5 "data/maps/MercyTown/scripts.pory"
	.string "{DOWN_ARROW}: Route 7\p"
	.string "To Sunday Cave and Crystal Stream City.$"

MercyTown_Route8Sign_Text_0:
# 12 "data/maps/MercyTown/scripts.pory"
	.string "{RIGHT_ARROW}: Route 8\p"
	.string "To Portrait Town.$"

MercyTown_ConcertHallSign_Text_0:
# 19 "data/maps/MercyTown/scripts.pory"
	.string "MERCY TOWN CONCERT HALL\p"
	.string "CMAT IS WAITING FOR YOU!$"

MercyTown_WelcomeToMercyTownSign_Text_0:
# 26 "data/maps/MercyTown/scripts.pory"
	.string "Welcome to Mercy Town!\p"
	.string "A stop on the road, take a break and\n"
	.string "rest your feet.$"
