Godzilland_MapScripts::
	.byte 0


Godzilland_CitySign::
# 4 "data/maps/Godzilland/scripts.pory"
	lock
# 5 "data/maps/Godzilland/scripts.pory"
	msgbox Godzilland_CitySign_Text_0, MSGBOX_AUTOCLOSE
# 6 "data/maps/Godzilland/scripts.pory"
	releaseall
	end


Godzilland_Route5Sign::
# 11 "data/maps/Godzilland/scripts.pory"
	lock
# 12 "data/maps/Godzilland/scripts.pory"
	msgbox Godzilland_Route5Sign_Text_0, MSGBOX_AUTOCLOSE
# 13 "data/maps/Godzilland/scripts.pory"
	releaseall
	end


Godzilland_HarbourSign::
# 18 "data/maps/Godzilland/scripts.pory"
	lock
# 19 "data/maps/Godzilland/scripts.pory"
	msgbox Godzilland_HarbourSign_Text_0, MSGBOX_AUTOCLOSE
# 20 "data/maps/Godzilland/scripts.pory"
	releaseall
	end


Godzilland_ConcertHallSign::
# 25 "data/maps/Godzilland/scripts.pory"
	lock
# 26 "data/maps/Godzilland/scripts.pory"
	msgbox Godzilland_ConcertHallSign_Text_0, MSGBOX_AUTOCLOSE
# 27 "data/maps/Godzilland/scripts.pory"
	releaseall
	end


Godzilland_CitySign_Text_0:
# 5 "data/maps/Godzilland/scripts.pory"
	.string "Welcome to Godzilland!\p"
	.string "Gateway to the unreleased archipelago!$"

Godzilland_Route5Sign_Text_0:
# 12 "data/maps/Godzilland/scripts.pory"
	.string "{DOWN_ARROW}: Route 5.$"

Godzilland_HarbourSign_Text_0:
# 19 "data/maps/Godzilland/scripts.pory"
	.string "Godzilland Harbour.\p"
	.string "Next departure: Beautiful Port.$"

Godzilland_ConcertHallSign_Text_0:
# 26 "data/maps/Godzilland/scripts.pory"
	.string "GODZILLAND CONCERT HALL\p"
	.string "CURRENT RESIDENT: ST.VINCENT$"
