Interlude_UpperDeck_MapScripts::
	.byte 0


InterludeRooftop_Ness::
# 4 "data/maps/Interlude_UpperDeck/scripts.pory"
	lock
# 5 "data/maps/Interlude_UpperDeck/scripts.pory"
	faceplayer
# 6 "data/maps/Interlude_UpperDeck/scripts.pory"
	msgbox InterludeRooftop_Ness_Text_0
# 7 "data/maps/Interlude_UpperDeck/scripts.pory"
	release
	end


InterludeRooftop_Ness_Text_0:
# 6 "data/maps/Interlude_UpperDeck/scripts.pory"
	.string "NESS: Most people on the boat want to\n"
	.string "battle, I came up here because it's more\l"
	.string "peaceful.$"
