# 1 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 2 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_MapScripts::
# 3 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 5 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_EventScript_DevonEmployee::
# 6 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones, MSGBOX_NPC
# 7 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	end
# 8 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 9 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones, MSGBOX_NPC
# 11 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	end
# 12 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 13 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones:
# 14 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I was expecting the challenge to\n"
# 15 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "cause a mess in town, with all those \l"
# 16 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "trainers coming to try their luck. \p"
# 17 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "But in the end it's nice, everyone \n"
# 18 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "is friendly and respectful!$"
# 19 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 20 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones:
# 21 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "Hozier is such a nice person!\p"
# 22 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I see him sometimes when I go \n"
# 23 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "shopping.$"
