Route10_MapScripts::
	.byte 0


Route10_SwimmerF::
# 4 "data/maps/Route10/scripts.pory"
	trainerbattle_single TRAINER_DENISE, Route10_SwimmerF_Text_0, Route10_SwimmerF_Text_1
# 5 "data/maps/Route10/scripts.pory"
	msgbox Route10_SwimmerF_Text_2, MSGBOX_AUTOCLOSE
	return


Route10_SwimmerM::
# 9 "data/maps/Route10/scripts.pory"
	trainerbattle_single TRAINER_LUIS, Route10_SwimmerM_Text_0, Route10_SwimmerM_Text_1
# 10 "data/maps/Route10/scripts.pory"
	msgbox Route10_SwimmerM_Text_2, MSGBOX_AUTOCLOSE
	return


Route10_BattleGirl::
# 14 "data/maps/Route10/scripts.pory"
	trainerbattle_single TRAINER_LAURA, Route10_BattleGirl_Text_0, Route10_BattleGirl_Text_1
# 15 "data/maps/Route10/scripts.pory"
	msgbox Route10_BattleGirl_Text_2, MSGBOX_AUTOCLOSE
	return


Route10_Tuber::
# 19 "data/maps/Route10/scripts.pory"
	trainerbattle_single TRAINER_AUSTINA, Route10_Tuber_Text_0, Route10_Tuber_Text_1
# 20 "data/maps/Route10/scripts.pory"
	msgbox Route10_Tuber_Text_2, MSGBOX_AUTOCLOSE
	return


Route10_SchoolGirl::
# 24 "data/maps/Route10/scripts.pory"
	trainerbattle_single TRAINER_GEORGIE, Route10_SchoolGirl_Text_0, Route10_SchoolGirl_Text_1
# 25 "data/maps/Route10/scripts.pory"
	msgbox Route10_SchoolGirl_Text_2, MSGBOX_AUTOCLOSE
	return


Route10_Psychic::
# 29 "data/maps/Route10/scripts.pory"
	trainerbattle_single TRAINER_PRESTON, Route10_Psychic_Text_0, Route10_Psychic_Text_1
# 30 "data/maps/Route10/scripts.pory"
	msgbox Route10_Psychic_Text_2, MSGBOX_AUTOCLOSE
	return


Route10_SwimmerF_Text_0:
# 4 "data/maps/Route10/scripts.pory"
	.string "The water is so warm, you should come\n"
	.string "swim!$"

Route10_SwimmerF_Text_1:
# 4 "data/maps/Route10/scripts.pory"
	.string "Not everyone likes swimming I guess…$"

Route10_SwimmerF_Text_2:
# 5 "data/maps/Route10/scripts.pory"
	.string "The water is the perfect temperature\n"
	.string "here!$"

Route10_SwimmerM_Text_0:
# 9 "data/maps/Route10/scripts.pory"
	.string "I can hold my breath for a minute!$"

Route10_SwimmerM_Text_1:
# 9 "data/maps/Route10/scripts.pory"
	.string "Gasp!$"

Route10_SwimmerM_Text_2:
# 10 "data/maps/Route10/scripts.pory"
	.string "The longest I've held my breath is a\n"
	.string "minute and six seconds!$"

Route10_BattleGirl_Text_0:
# 14 "data/maps/Route10/scripts.pory"
	.string "My POKéMON are growing stronger!$"

Route10_BattleGirl_Text_1:
# 14 "data/maps/Route10/scripts.pory"
	.string "I have to grow stronger, too.$"

Route10_BattleGirl_Text_2:
# 15 "data/maps/Route10/scripts.pory"
	.string "There's no secret, the only way to get\n"
	.string "stronger is to train!$"

Route10_Tuber_Text_0:
# 19 "data/maps/Route10/scripts.pory"
	.string "I put a message in a bottle and threw it\n"
	.string "out to the sea.$"

Route10_Tuber_Text_1:
# 19 "data/maps/Route10/scripts.pory"
	.string "Maybe it got lost…$"

Route10_Tuber_Text_2:
# 20 "data/maps/Route10/scripts.pory"
	.string "Maybe if I keep throwing messages in\n"
	.string "bottles I'll make new friends…$"

Route10_SchoolGirl_Text_0:
# 24 "data/maps/Route10/scripts.pory"
	.string "I found this bottle with a message in\n"
	.string "it.\p"
	.string "Did you send it?$"

Route10_SchoolGirl_Text_1:
# 24 "data/maps/Route10/scripts.pory"
	.string "Must be from someone else, then…$"

Route10_SchoolGirl_Text_2:
# 25 "data/maps/Route10/scripts.pory"
	.string "I wonder who sent this message, maybe I\n"
	.string "could become their friend…$"

Route10_Psychic_Text_0:
# 29 "data/maps/Route10/scripts.pory"
	.string "The repetitive sound of the sea\n"
	.string "enhances my powers, I'm unstoppable!$"

Route10_Psychic_Text_1:
# 29 "data/maps/Route10/scripts.pory"
	.string "Maybe the sea enhances your powers\n"
	.string "too…$"

Route10_Psychic_Text_2:
# 30 "data/maps/Route10/scripts.pory"
	.string "The waves are so relaxing it makes it\n"
	.string "easy to focus.\p"
	.string "Moore focus means more power!$"
