# 1 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 2 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_MapScripts::
# 3 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route111_OldLadysRestStop_OnTransition
# 4 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.byte 0
# 5 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 6 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_OnTransition:
# 7 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	setflag FLAG_LANDMARK_OLD_LADY_REST_SHOP
# 8 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	setrespawn HEAL_LOCATION_MIRROR_LAKE
# 9 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	end
# 10 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 11 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_EventScript_OldLady::
# 12 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	lock
# 13 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	faceplayer
# 14 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox Route111_OldLadysRestStop_Text_RestUpHere, MSGBOX_YESNO
# 15 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route111_OldLadysRestStop_EventScript_Rest
# 16 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	goto_if_eq VAR_RESULT, NO, Route111_OldLadysRestStop_EventScript_DeclineRest
# 17 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	end
# 18 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 19 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_EventScript_Rest::
# 20 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox Route111_OldLadysRestStop_Text_TakeYourTimeRestUp, MSGBOX_DEFAULT
# 21 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	closemessage
# 22 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	call Common_EventScript_OutOfCenterPartyHeal
# 23 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox Route111_OldLadysRestStop_Text_StillTiredTakeAnotherRest, MSGBOX_YESNO
# 24 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route111_OldLadysRestStop_EventScript_Rest
# 25 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	goto_if_eq VAR_RESULT, NO, Route111_OldLadysRestStop_EventScript_DeclineRest
# 26 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	end
# 27 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 28 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_EventScript_DeclineRest::
# 29 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox Route111_OldLadysRestStop_Text_DontNeedToBeShy, MSGBOX_DEFAULT
# 30 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	release
# 31 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	end
# 32 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 33 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_Text_RestUpHere:
# 34 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Oh, dear, dear.\n"
# 35 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Aren't your POKéMON exhausted?\p"
# 36 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "If you'd like, rest up here.\n"
# 37 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "That's a fine idea! You should do that.$"
# 38 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 39 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_Text_TakeYourTimeRestUp:
# 40 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "That's right.\n"
# 41 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Take your time and rest up!$"
# 42 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 43 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_Text_StillTiredTakeAnotherRest:
# 44 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Oh, dear, dear.\n"
# 45 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Are your POKéMON still tired?\p"
# 46 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "You should take another rest here.\n"
# 47 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "That's a fine idea. You should do that.$"
# 48 "data/maps/Route111_OldLadysRestStop/scripts.pory"

# 49 "data/maps/Route111_OldLadysRestStop/scripts.pory"
Route111_OldLadysRestStop_Text_DontNeedToBeShy:
# 50 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Is that so?\n"
# 51 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "You don't need to be shy about it.$"

OldLadysRestStop_Girl::
# 55 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	lock
# 56 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	faceplayer
# 57 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	goto_if_set FLAG_DEFEATED_SOOTOPOLIS_GYM, OldLadysRestStop_Girl_2
# 61 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox ItWasDavidBowie, MSGBOX_AUTOCLOSE
OldLadysRestStop_Girl_1:
# 63 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	release
	end

OldLadysRestStop_Girl_2:
# 58 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox StrangeNoises, MSGBOX_AUTOCLOSE
	goto OldLadysRestStop_Girl_1


StrangeNoises::
# 67 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "We've been hearing weird noises around \n"
	.string "here. \p"
	.string "No idea where they're from, but it \n"
	.string "almost sounds like music if you listen \l"
	.string "closely… $"

ItWasDavidBowie::
# 75 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "The noises stopped… \p"
	.string "What? You figured it out? \p"
	.string "A musician under the waterfall? \p"
	.string "This place is so strange… $"
