NightingaleCity_MapScripts::
	.byte 0


NightingaleCity_PubSign::
# 4 "data/maps/NightingaleCity/scripts.pory"
	lock
# 5 "data/maps/NightingaleCity/scripts.pory"
	msgbox NightingaleCity_PubSign_Text_0
# 6 "data/maps/NightingaleCity/scripts.pory"
	release
	end


NightingaleCity_PubSign_Text_0:
# 5 "data/maps/NightingaleCity/scripts.pory"
	.string "The Nightingale Pub\p"
	.string "Fresh drinks and good vibes!$"
